import test from 'node:test';
import assert from 'node:assert/strict';
import { createPublicKey, verify } from 'node:crypto';
import { copyFile, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { basename, dirname, join, resolve } from 'node:path';

test('owner CLI protects keys and issues verifiable installation-bound licenses', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'diffrook-license-tool-'));
  t.after(async () => {
    const target = resolve(directory);
    assert.equal(dirname(target), resolve(tmpdir()));
    assert.ok(basename(target).startsWith('diffrook-license-tool-'));
    await rm(target, { recursive: true, force: true });
  });
  await mkdir(join(directory, 'scripts'));
  await mkdir(join(directory, 'src'));
  await copyFile(new URL('./license.mjs', import.meta.url), join(directory, 'scripts/license.mjs'));
  const run = (...args) => spawnSync(process.execPath, [join(directory, 'scripts/license.mjs'), ...args], { encoding: 'utf8', cwd: directory });
  assert.equal(run('init').status, 0);
  const originalKey = await readFile(join(directory, 'secrets/license-signing-key.pem'));
  assert.notEqual(run('init').status, 0);
  assert.deepEqual(await readFile(join(directory, 'secrets/license-signing-key.pem')), originalKey);
  const id = '12345678-1234-4321-9876-123456789abc';
  const output = join(directory, 'customer.json');
  const argumentsList = ['issue', '--installation', id, '--customer', 'Test customer', '--users', '20', '--automations', '100', '--expires', '2099-01-01T00:00:00Z', '--out', output];
  assert.equal(run(...argumentsList).status, 0);
  const envelope = JSON.parse(await readFile(output, 'utf8'));
  const payload = Buffer.from(envelope.payload, 'base64url');
  const claims = JSON.parse(payload);
  assert.equal(claims.installation_id, id);
  assert.equal(claims.max_users, 20);
  assert.equal(claims.max_automations, 100);
  assert.equal(claims.product, 'diffrook');
  const publicBytes = Buffer.from((await readFile(join(directory, 'src/license-public-key.hex'), 'utf8')).trim(), 'hex');
  const key = createPublicKey({ format: 'jwk', key: { kty: 'OKP', crv: 'Ed25519', x: publicBytes.toString('base64url') } });
  assert.ok(verify(null, Buffer.concat([Buffer.from('diffrook-license-v1\0'), payload]), key, Buffer.from(envelope.signature, 'base64url')));
  const saved = await readFile(output);
  assert.notEqual(run(...argumentsList).status, 0);
  assert.deepEqual(await readFile(output), saved);
  assert.notEqual(run('issue', '--installation', id, '--customer', 'Test', '--users', '0', '--out', join(directory, 'invalid.json')).status, 0);
  assert.notEqual(run('issue', '--installation', id, '--customer', 'Test', '--expires', '2000-01-01', '--out', join(directory, 'expired.json')).status, 0);
  await writeFile(join(directory, 'src/license-public-key.hex'), '00'.repeat(32));
  assert.notEqual(run('issue', '--installation', id, '--customer', 'Test', '--out', join(directory, 'wrong-key.json')).status, 0);
});
